# -*- coding: utf-8 -*-
"""guessing-game-challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/GrandpaCrunkle/a2547563393fa02197acfc5297e49d1e/guessing-game-challenge.ipynb
"""

import random

def guessing_game():
  randomnumber = random.randint(1,100)
  rules = 'You must guess the random number if you are within 10 of the number or outside of 10 of the number you are trying to guess.'
  guess = None
  guess_count = 0
  print(rules)
  while True:
    guess = int(input('Input your Guess\n'))
    guess_count += 1
    if guess == randomnumber:
      print(f'Congratulations you guessed the right number which was {randomnumber} it took {guess_count} guesses')
      break
    elif abs(randomnumber - guess) <= 10:
      print('Your guess is within 10, guess again.')
    elif abs(randomnumber - guess) > 10:
      print('Your guess is outside of 10, guess again.')
    elif guess > 100 or guess < 1:
      print('Outside of number range of 1-100')
guessing_game()